dist: trusty

group: edge

language: java

sudo: required

jdk: openjdk8

install:
   - export MAVEN_HOME=`mvn --version | grep 'Maven home' | sed -e 's/Maven h.* //'`

script:
  - ./.travis/build.sh

after_success:
  - cd .. && ./.travis/travis-deploy.sh

branch:
  only:
    - master
